import { Fertigkeit, FertigkeitType } from "../models/items/fertigkeit";

export const DEFAULT_FERTIGKEITEN: Array<Fertigkeit & { name: string }> = [
  {
    attributEins: "BEW",
    attributZwei: "STR",
    punkte: 0,
    mod: 0,
    name: "Akrobatik",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "MYS",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Alchemie",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Anführen",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "MYS",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Arkane Kunde",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "BEW",
    attributZwei: "STR",
    punkte: 0,
    mod: 0,
    name: "Athletik",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Darbietung",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Diplomatie",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Edelhandwerk",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Empathie",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Entschlossenheit",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "BEW",
    punkte: 0,
    mod: 0,
    name: "Fingerfertigkeit",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "MYS",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Geschichte & Mythen",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "KON",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Handwerk",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Heilkunde",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "BEW",
    attributZwei: "INT",
    punkte: 0,
    mod: 0,
    name: "Heimlichkeit",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "KON",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Jagdkunst",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Länderkunde",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "VER",
    punkte: 0,
    mod: 0,
    name: "Naturkunde",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Redegewandheit",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "BEW",
    punkte: 0,
    mod: 0,
    name: "Schlösser & Fallen",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "STR",
    attributZwei: "KON",
    punkte: 0,
    mod: 0,
    name: "Schwimmen",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "BEW",
    attributZwei: "KON",
    punkte: 0,
    mod: 0,
    name: "Seefahrt",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "INT",
    punkte: 0,
    mod: 0,
    name: "Straßenkunde",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "AUS",
    attributZwei: "BEW",
    punkte: 0,
    mod: 0,
    name: "Tierführung",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "KON",
    punkte: 0,
    mod: 0,
    name: "Überleben",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "INT",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Wahrnehmung",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
  {
    attributEins: "KON",
    attributZwei: "WIL",
    punkte: 0,
    mod: 0,
    name: "Zähigkeit",
    beschreibung: "",
    regelwerk: "",
    seite: 0,
    type: FertigkeitType.Allgemein,
  },
];
